// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: user.proto

package server

import (
	"context"

	"gozero_mall_study/service/user/rpc/internal/logic"
	"gozero_mall_study/service/user/rpc/internal/svc"
	"gozero_mall_study/service/user/rpc/userclient"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	userclient.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *userclient.LoginRequest) (*userclient.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *userclient.RegisterRequest) (*userclient.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *userclient.UserInfoRequest) (*userclient.UserInfoResponse, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
