// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.23.3
// source: proto/duo_fu_wu.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint32 `protobuf:"fixed32,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_duo_fu_wu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_duo_fu_wu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_duo_fu_wu_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type HellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *HellResponse) Reset() {
	*x = HellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_duo_fu_wu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HellResponse) ProtoMessage() {}

func (x *HellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_duo_fu_wu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HellResponse.ProtoReflect.Descriptor instead.
func (*HellResponse) Descriptor() ([]byte, []int) {
	return file_proto_duo_fu_wu_proto_rawDescGZIP(), []int{1}
}

func (x *HellResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_duo_fu_wu_proto protoreflect.FileDescriptor

var file_proto_duo_fu_wu_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x75, 0x6f, 0x5f, 0x66, 0x75, 0x5f, 0x77,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x74,
	0x75, 0x64, 0x79, 0x22, 0x1e, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x42, 0x0a, 0x03, 0x53, 0x61, 0x79, 0x12, 0x3b,
	0x0a, 0x03, 0x53, 0x61, 0x79, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x74, 0x75,
	0x64, 0x79, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x44, 0x0a, 0x04, 0x4c,
	0x6f, 0x6f, 0x6b, 0x12, 0x3c, 0x0a, 0x04, 0x4c, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x74, 0x75,
	0x64, 0x79, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_duo_fu_wu_proto_rawDescOnce sync.Once
	file_proto_duo_fu_wu_proto_rawDescData = file_proto_duo_fu_wu_proto_rawDesc
)

func file_proto_duo_fu_wu_proto_rawDescGZIP() []byte {
	file_proto_duo_fu_wu_proto_rawDescOnce.Do(func() {
		file_proto_duo_fu_wu_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_duo_fu_wu_proto_rawDescData)
	})
	return file_proto_duo_fu_wu_proto_rawDescData
}

var file_proto_duo_fu_wu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_duo_fu_wu_proto_goTypes = []interface{}{
	(*HelloRequest)(nil), // 0: grpc_study.HelloRequest
	(*HellResponse)(nil), // 1: grpc_study.HellResponse
}
var file_proto_duo_fu_wu_proto_depIdxs = []int32{
	0, // 0: grpc_study.Say.Say:input_type -> grpc_study.HelloRequest
	0, // 1: grpc_study.Look.Look:input_type -> grpc_study.HelloRequest
	1, // 2: grpc_study.Say.Say:output_type -> grpc_study.HellResponse
	1, // 3: grpc_study.Look.Look:output_type -> grpc_study.HellResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_duo_fu_wu_proto_init() }
func file_proto_duo_fu_wu_proto_init() {
	if File_proto_duo_fu_wu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_duo_fu_wu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_duo_fu_wu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_duo_fu_wu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_duo_fu_wu_proto_goTypes,
		DependencyIndexes: file_proto_duo_fu_wu_proto_depIdxs,
		MessageInfos:      file_proto_duo_fu_wu_proto_msgTypes,
	}.Build()
	File_proto_duo_fu_wu_proto = out.File
	file_proto_duo_fu_wu_proto_rawDesc = nil
	file_proto_duo_fu_wu_proto_goTypes = nil
	file_proto_duo_fu_wu_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SayClient is the client API for Say service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SayClient interface {
	Say(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HellResponse, error)
}

type sayClient struct {
	cc grpc.ClientConnInterface
}

func NewSayClient(cc grpc.ClientConnInterface) SayClient {
	return &sayClient{cc}
}

func (c *sayClient) Say(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HellResponse, error) {
	out := new(HellResponse)
	err := c.cc.Invoke(ctx, "/grpc_study.Say/Say", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayServer is the server API for Say service.
type SayServer interface {
	Say(context.Context, *HelloRequest) (*HellResponse, error)
}

// UnimplementedSayServer can be embedded to have forward compatible implementations.
type UnimplementedSayServer struct {
}

func (*UnimplementedSayServer) Say(context.Context, *HelloRequest) (*HellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Say not implemented")
}

func RegisterSayServer(s *grpc.Server, srv SayServer) {
	s.RegisterService(&_Say_serviceDesc, srv)
}

func _Say_Say_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayServer).Say(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_study.Say/Say",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayServer).Say(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Say_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_study.Say",
	HandlerType: (*SayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _Say_Say_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/duo_fu_wu.proto",
}

// LookClient is the client API for Look service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LookClient interface {
	Look(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HellResponse, error)
}

type lookClient struct {
	cc grpc.ClientConnInterface
}

func NewLookClient(cc grpc.ClientConnInterface) LookClient {
	return &lookClient{cc}
}

func (c *lookClient) Look(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HellResponse, error) {
	out := new(HellResponse)
	err := c.cc.Invoke(ctx, "/grpc_study.Look/Look", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LookServer is the server API for Look service.
type LookServer interface {
	Look(context.Context, *HelloRequest) (*HellResponse, error)
}

// UnimplementedLookServer can be embedded to have forward compatible implementations.
type UnimplementedLookServer struct {
}

func (*UnimplementedLookServer) Look(context.Context, *HelloRequest) (*HellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Look not implemented")
}

func RegisterLookServer(s *grpc.Server, srv LookServer) {
	s.RegisterService(&_Look_serviceDesc, srv)
}

func _Look_Look_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LookServer).Look(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_study.Look/Look",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LookServer).Look(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Look_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_study.Look",
	HandlerType: (*LookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Look",
			Handler:    _Look_Look_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/duo_fu_wu.proto",
}
